#!/bin/bash -l
#SBATCH --job-name=redis_b175afb4
#SBATCH --time=01:00:00
#SBATCH --qos=default
#SBATCH --partition=cpu
#SBATCH --account=p200981
#SBATCH --nodes=1
#SBATCH --mem=4GB
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1

# Load required modules
module add Apptainer

# Set environment variables
export REDIS_PERSISTENCE=both

mkdir -p $HOME/containers
# Container management
if [ ! -f "$HOME/containers/redis_latest.sif" ]; then
    echo "Container $HOME/containers/redis_latest.sif not found, building from docker://redis:7-alpine..."
    echo "Starting container build at $(date)"
    apptainer build $HOME/containers/redis_latest.sif docker://redis:7-alpine
    if [ $? -eq 0 ]; then
        echo "Container built successfully at $(date)"
    else
        echo "Container build failed at $(date)"
        exit 1
    fi
else
    echo "Container $HOME/containers/redis_latest.sif already exists"
fi

# Redis setup
mkdir -p $HOME/redis/data
mkdir -p $HOME/redis/config

# Create Redis configuration file
cat > $HOME/redis/config/redis.conf << 'EOF'
# Redis configuration generated by HPC Orchestrator

# Network
bind 0.0.0.0
port 6379
protected-mode no

# General
daemonize no
pidfile /var/run/redis.pid
loglevel notice
logfile ""

# Directory for data
dir /redis/data

# Memory Management
maxmemory-policy allkeys-lru

# AOF Persistence
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

# RDB Persistence
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
EOF

echo 'Redis configuration created:'
cat $HOME/redis/config/redis.conf

# Start the redis service
apptainer exec --bind $HOME/redis/data:/redis/data --bind $HOME/redis/config:/redis/config --env REDIS_PERSISTENCE=both $HOME/containers/redis_latest.sif redis-server /redis/config/redis.conf &

# Wait for Redis to start
sleep 5

# Get the Redis process ID
REDIS_PID=$!

# Display Redis endpoint
echo '========================================='
echo 'Redis is running on:'
echo "redis://$(hostname):6379"
echo '========================================='

# Check if Redis is responding
for i in {1..10}; do
    if redis-cli  -h localhost -p 6379 ping > /dev/null 2>&1; then
        echo "Redis is ready!"
        redis-cli  -h localhost -p 6379 INFO server | grep redis_version
        break
    fi
    echo "Waiting for Redis to be ready... ($i/10)"
    sleep 3
done

# Monitor Redis process
echo 'Monitoring Redis... (press Ctrl+C to stop)'
while kill -0 $REDIS_PID 2>/dev/null; do
    sleep 60
    echo "Redis still running on $(hostname):6379"
    redis-cli  -h localhost -p 6379 INFO stats | grep total_connections_received || true
done

echo 'Redis service finished'